CREATE TABLE agendamento
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status        VARCHAR(255),
    tipo_especial BOOLEAN                                 NOT NULL,
    animal_id     BIGINT,
    data_vaga     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_agendamento PRIMARY KEY (id)
);

CREATE TABLE animal
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome            VARCHAR(255),
    sexo            VARCHAR(255),
    alergias        VARCHAR(255),
    data_nascimento date,
    imagem          VARCHAR(255),
    castrado        BOOLEAN                                 NOT NULL,
    peso            DOUBLE PRECISION                        NOT NULL,
    numero_ficha    VARCHAR(255),
    raca_id         BIGINT,
    tutor_id        BIGINT,
    CONSTRAINT pk_animal PRIMARY KEY (id)
);

CREATE TABLE area
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo_area VARCHAR(255),
    orgao_id    BIGINT,
    CONSTRAINT pk_area PRIMARY KEY (id)
);

CREATE TABLE aviso
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    texto      VARCHAR(255),
    habilitado BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_aviso PRIMARY KEY (id)
);

CREATE TABLE campo_laudo
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao      VARCHAR(255),
    orgao_id       BIGINT,
    campo_laudo_id BIGINT,
    CONSTRAINT pk_campolaudo PRIMARY KEY (id)
);

CREATE TABLE campo_laudo_microscopia
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao                  VARCHAR(255),
    processamento              SMALLINT,
    orgao_id                   BIGINT,
    campo_laudo_microscopia_id BIGINT,
    CONSTRAINT pk_campolaudomicroscopia PRIMARY KEY (id)
);

CREATE TABLE cancelamento
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao         VARCHAR(255),
    data_vaga         TIMESTAMP WITHOUT TIME ZONE,
    data_cancelamento TIMESTAMP WITHOUT TIME ZONE,
    especialidade_id  BIGINT,
    agendamento_id    BIGINT,
    vaga_id           BIGINT,
    CONSTRAINT pk_cancelamento PRIMARY KEY (id)
);

CREATE TABLE consulta
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    peso_atual                   DOUBLE PRECISION,
    idade_atual                  DOUBLE PRECISION,
    proxima_consulta             BOOLEAN                                 NOT NULL,
    encaminhamento_id            BIGINT,
    queixa_principal             VARCHAR(255),
    tipo                         BOOLEAN                                 NOT NULL,
    alteracoes_clinicas_diversas VARCHAR(255),
    suspeitas_clinicas           VARCHAR(255),
    alimentacao                  VARCHAR(255),
    medico_id                    BIGINT,
    animal_id                    BIGINT,
    data_vaga                    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_consulta PRIMARY KEY (id)
);

CREATE TABLE consulta_estagiario
(
    consulta_id   BIGINT NOT NULL,
    estagiario_id BIGINT NOT NULL
);

CREATE TABLE cronograma
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome              VARCHAR(255),
    horarios_json     OID,
    tempo_atendimento DOUBLE PRECISION,
    medico_id         BIGINT,
    cronograma_id     BIGINT,
    tipo_consulta_id  BIGINT,
    CONSTRAINT pk_cronograma PRIMARY KEY (id)
);

CREATE TABLE endereco
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cep    VARCHAR(255),
    rua    VARCHAR(255),
    estado VARCHAR(255),
    cidade VARCHAR(255),
    numero INTEGER                                 NOT NULL,
    bairro VARCHAR(255),
    CONSTRAINT pk_endereco PRIMARY KEY (id)
);

CREATE TABLE especialidade
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255),
    descricao VARCHAR(255),
    CONSTRAINT pk_especialidade PRIMARY KEY (id)
);

CREATE TABLE especie
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255),
    descricao VARCHAR(255),
    area_id   BIGINT,
    CONSTRAINT pk_especie PRIMARY KEY (id)
);

CREATE TABLE estagiario
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome        VARCHAR(255),
    cpf         VARCHAR(255),
    periodo     VARCHAR(255),
    obrigatorio BOOLEAN                                 NOT NULL,
    ativo       BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_estagiario PRIMARY KEY (id)
);

CREATE TABLE etapa
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    responsavel VARCHAR(255),
    observacoes VARCHAR(255),
    data_hora   TIMESTAMP WITHOUT TIME ZONE,
    concluido   BOOLEAN,
    CONSTRAINT pk_etapa PRIMARY KEY (id)
);

CREATE TABLE ficha
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255),
    conteudo  JSONB,
    data_hora TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_ficha PRIMARY KEY (id)
);

CREATE TABLE ficha_solicitacao_servico
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ficha_clinica              VARCHAR(255),
    codigo_patologia           VARCHAR(255),
    tipo_servico               SMALLINT,
    data_hora_obito            TIMESTAMP WITHOUT TIME ZONE,
    data_recebimento           TIMESTAMP WITHOUT TIME ZONE,
    estado_conservacao         SMALLINT,
    acondicionamento           SMALLINT,
    material                   SMALLINT,
    eutanasia                  BOOLEAN,
    historico                  VARCHAR(255),
    caracteristicas_adicionais VARCHAR(255),
    "animal_id)"               BIGINT,
    tutor_id                   BIGINT,
    medico_id                  BIGINT,
    CONSTRAINT pk_fichasolicitacaoservico PRIMARY KEY (id)
);

CREATE TABLE foto
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo    VARCHAR(255),
    foto_path VARCHAR(255),
    CONSTRAINT pk_foto PRIMARY KEY (id)
);

CREATE TABLE instituicao
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome        VARCHAR(255),
    endereco_id BIGINT,
    CONSTRAINT pk_instituicao PRIMARY KEY (id)
);

CREATE TABLE laudo_necropsia
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    conclusao                    VARCHAR(255),
    ficha_solicitacao_servico_id BIGINT,
    CONSTRAINT pk_laudonecropsia PRIMARY KEY (id)
);

CREATE TABLE laudo_necropsia_estagiario
(
    laudo_necropsia_id BIGINT NOT NULL,
    estagiario_id      BIGINT NOT NULL
);

CREATE TABLE laudo_necropsia_foto
(
    laudo_necropsia_id BIGINT NOT NULL,
    foto_id            BIGINT NOT NULL
);

CREATE TABLE material_coletado
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo   VARCHAR(255),
    nome     VARCHAR(255),
    orgao_id BIGINT,
    CONSTRAINT pk_materialcoletado PRIMARY KEY (id)
);

CREATE TABLE medico
(
    id             BIGINT NOT NULL,
    crmv           VARCHAR(255),
    instituicao_id BIGINT,
    CONSTRAINT pk_medico PRIMARY KEY (id)
);

CREATE TABLE medico_especialidade
(
    medico_id        BIGINT NOT NULL,
    especialidade_id BIGINT NOT NULL
);

CREATE TABLE orgao
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome       VARCHAR(255),
    sexo_macho BOOLEAN,
    sexo_femea BOOLEAN,
    foto_id    BIGINT,
    CONSTRAINT pk_orgao PRIMARY KEY (id)
);

CREATE TABLE raca
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome       VARCHAR(255),
    porte      VARCHAR(255),
    descricao  VARCHAR(255),
    especie_id BIGINT,
    CONSTRAINT pk_raca PRIMARY KEY (id)
);

CREATE TABLE tipo_consulta
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo VARCHAR(255),
    CONSTRAINT pk_tipoconsulta PRIMARY KEY (id)
);

CREATE TABLE tutor
(
    id BIGINT NOT NULL,
    rg VARCHAR(255),
    CONSTRAINT pk_tutor PRIMARY KEY (id)
);

CREATE TABLE usuario
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email       VARCHAR(255),
    cpf         VARCHAR(255),
    telefone    VARCHAR(255),
    nome        VARCHAR(255),
    user_id     VARCHAR(255),
    deleted     BOOLEAN,
    endereco_id BIGINT,
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

CREATE TABLE vaga
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_hora        TIMESTAMP WITHOUT TIME ZONE,
    status           VARCHAR(255),
    especialidade_id BIGINT,
    medico_id        BIGINT,
    consulta_id      BIGINT,
    agendamento_id   BIGINT,
    tipo_consulta_id BIGINT,
    cronograma_id    BIGINT,
    CONSTRAINT pk_vaga PRIMARY KEY (id)
);

ALTER TABLE ficha_solicitacao_servico
    ADD CONSTRAINT "uc_fichasolicitacaoservico_animal_id)" UNIQUE ("animal_id)");

ALTER TABLE laudo_necropsia_foto
    ADD CONSTRAINT uc_laudo_necropsia_foto_foto UNIQUE (foto_id);

ALTER TABLE agendamento
    ADD CONSTRAINT FK_AGENDAMENTO_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animal (id);

ALTER TABLE animal
    ADD CONSTRAINT FK_ANIMAL_ON_RACA FOREIGN KEY (raca_id) REFERENCES raca (id);

ALTER TABLE animal
    ADD CONSTRAINT FK_ANIMAL_ON_TUTOR FOREIGN KEY (tutor_id) REFERENCES tutor (id);

ALTER TABLE area
    ADD CONSTRAINT FK_AREA_ON_ORGAO FOREIGN KEY (orgao_id) REFERENCES orgao (id);

ALTER TABLE campo_laudo_microscopia
    ADD CONSTRAINT FK_CAMPOLAUDOMICROSCOPIA_ON_CAMPOLAUDOMICROSCOPIA FOREIGN KEY (campo_laudo_microscopia_id) REFERENCES laudo_necropsia (id);

ALTER TABLE campo_laudo_microscopia
    ADD CONSTRAINT FK_CAMPOLAUDOMICROSCOPIA_ON_ORGAO FOREIGN KEY (orgao_id) REFERENCES orgao (id);

ALTER TABLE campo_laudo
    ADD CONSTRAINT FK_CAMPOLAUDO_ON_CAMPOLAUDO FOREIGN KEY (campo_laudo_id) REFERENCES laudo_necropsia (id);

ALTER TABLE campo_laudo
    ADD CONSTRAINT FK_CAMPOLAUDO_ON_ORGAO FOREIGN KEY (orgao_id) REFERENCES orgao (id);

ALTER TABLE cancelamento
    ADD CONSTRAINT FK_CANCELAMENTO_ON_AGENDAMENTO FOREIGN KEY (agendamento_id) REFERENCES agendamento (id);

ALTER TABLE cancelamento
    ADD CONSTRAINT FK_CANCELAMENTO_ON_ESPECIALIDADE FOREIGN KEY (especialidade_id) REFERENCES especialidade (id);

ALTER TABLE cancelamento
    ADD CONSTRAINT FK_CANCELAMENTO_ON_VAGA FOREIGN KEY (vaga_id) REFERENCES vaga (id);

ALTER TABLE consulta
    ADD CONSTRAINT FK_CONSULTA_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animal (id);

ALTER TABLE consulta
    ADD CONSTRAINT FK_CONSULTA_ON_ENCAMINHAMENTO FOREIGN KEY (encaminhamento_id) REFERENCES especialidade (id);

ALTER TABLE consulta
    ADD CONSTRAINT FK_CONSULTA_ON_MEDICO FOREIGN KEY (medico_id) REFERENCES medico (id);

ALTER TABLE cronograma
    ADD CONSTRAINT FK_CRONOGRAMA_ON_CRONOGRAMA FOREIGN KEY (cronograma_id) REFERENCES especialidade (id);

ALTER TABLE cronograma
    ADD CONSTRAINT FK_CRONOGRAMA_ON_MEDICO FOREIGN KEY (medico_id) REFERENCES medico (id);

ALTER TABLE cronograma
    ADD CONSTRAINT FK_CRONOGRAMA_ON_TIPOCONSULTA FOREIGN KEY (tipo_consulta_id) REFERENCES tipo_consulta (id);

ALTER TABLE especie
    ADD CONSTRAINT FK_ESPECIE_ON_AREA FOREIGN KEY (area_id) REFERENCES area (id);

ALTER TABLE ficha_solicitacao_servico
    ADD CONSTRAINT "FK_FICHASOLICITACAOSERVICO_ON_ANIMAL_ID)" FOREIGN KEY ("animal_id)") REFERENCES animal (id);

ALTER TABLE ficha_solicitacao_servico
    ADD CONSTRAINT FK_FICHASOLICITACAOSERVICO_ON_MEDICO FOREIGN KEY (medico_id) REFERENCES medico (id);

ALTER TABLE ficha_solicitacao_servico
    ADD CONSTRAINT FK_FICHASOLICITACAOSERVICO_ON_TUTOR FOREIGN KEY (tutor_id) REFERENCES tutor (id);

ALTER TABLE instituicao
    ADD CONSTRAINT FK_INSTITUICAO_ON_ENDERECO FOREIGN KEY (endereco_id) REFERENCES endereco (id);

ALTER TABLE laudo_necropsia
    ADD CONSTRAINT FK_LAUDONECROPSIA_ON_FICHASOLICITACAOSERVICO FOREIGN KEY (ficha_solicitacao_servico_id) REFERENCES ficha_solicitacao_servico (id);

ALTER TABLE material_coletado
    ADD CONSTRAINT FK_MATERIALCOLETADO_ON_ORGAO FOREIGN KEY (orgao_id) REFERENCES orgao (id);

ALTER TABLE medico
    ADD CONSTRAINT FK_MEDICO_ON_ID FOREIGN KEY (id) REFERENCES usuario (id);

ALTER TABLE medico
    ADD CONSTRAINT FK_MEDICO_ON_INSTITUICAO FOREIGN KEY (instituicao_id) REFERENCES instituicao (id);

ALTER TABLE orgao
    ADD CONSTRAINT FK_ORGAO_ON_FOTO FOREIGN KEY (foto_id) REFERENCES foto (id);

ALTER TABLE raca
    ADD CONSTRAINT FK_RACA_ON_ESPECIE FOREIGN KEY (especie_id) REFERENCES especie (id);

ALTER TABLE tutor
    ADD CONSTRAINT FK_TUTOR_ON_ID FOREIGN KEY (id) REFERENCES usuario (id);

ALTER TABLE usuario
    ADD CONSTRAINT FK_USUARIO_ON_ENDERECO FOREIGN KEY (endereco_id) REFERENCES endereco (id);

ALTER TABLE vaga
    ADD CONSTRAINT FK_VAGA_ON_AGENDAMENTO FOREIGN KEY (agendamento_id) REFERENCES agendamento (id);

ALTER TABLE vaga
    ADD CONSTRAINT FK_VAGA_ON_CONSULTA FOREIGN KEY (consulta_id) REFERENCES consulta (id);

ALTER TABLE vaga
    ADD CONSTRAINT FK_VAGA_ON_CRONOGRAMA FOREIGN KEY (cronograma_id) REFERENCES cronograma (id);

ALTER TABLE vaga
    ADD CONSTRAINT FK_VAGA_ON_ESPECIALIDADE FOREIGN KEY (especialidade_id) REFERENCES especialidade (id);

ALTER TABLE vaga
    ADD CONSTRAINT FK_VAGA_ON_MEDICO FOREIGN KEY (medico_id) REFERENCES medico (id);

ALTER TABLE vaga
    ADD CONSTRAINT FK_VAGA_ON_TIPOCONSULTA FOREIGN KEY (tipo_consulta_id) REFERENCES tipo_consulta (id);

ALTER TABLE consulta_estagiario
    ADD CONSTRAINT fk_conest_on_consulta FOREIGN KEY (consulta_id) REFERENCES consulta (id);

ALTER TABLE consulta_estagiario
    ADD CONSTRAINT fk_conest_on_estagiario FOREIGN KEY (estagiario_id) REFERENCES estagiario (id);

ALTER TABLE laudo_necropsia_estagiario
    ADD CONSTRAINT fk_launecest_on_estagiario FOREIGN KEY (estagiario_id) REFERENCES estagiario (id);

ALTER TABLE laudo_necropsia_estagiario
    ADD CONSTRAINT fk_launecest_on_laudo_necropsia FOREIGN KEY (laudo_necropsia_id) REFERENCES laudo_necropsia (id);

ALTER TABLE laudo_necropsia_foto
    ADD CONSTRAINT fk_launecfot_on_foto FOREIGN KEY (foto_id) REFERENCES foto (id);

ALTER TABLE laudo_necropsia_foto
    ADD CONSTRAINT fk_launecfot_on_laudo_necropsia FOREIGN KEY (laudo_necropsia_id) REFERENCES laudo_necropsia (id);

ALTER TABLE medico_especialidade
    ADD CONSTRAINT fk_medesp_on_especialidade FOREIGN KEY (especialidade_id) REFERENCES especialidade (id);

ALTER TABLE medico_especialidade
    ADD CONSTRAINT fk_medesp_on_medico FOREIGN KEY (medico_id) REFERENCES medico (id);