files.storage: ./var/hvu/files/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banco
    username: postgres
    password: 1234
    auto-commit: false

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
           non_contextual_creation: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: app_lmts
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/lmts
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/lmts/protocol/openid-connect/certs

springdoc:
  api-docs:
    path: /api-doc/docs
  swagger-ui:
    path: /api-doc/swagger.html

server:
  port: 8081

common:
  front: http://localhost:3000/,https://lmtsteste06.ufape.edu.br/
  back: http://localhost:8081/,https://lmtsteste03.ufape.edu.br/
  docker: http://localhost:8000/,https://lmtsteste04.ufape.edu.br/

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://backend-db:5432/hvu
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/lmts/protocol/openid-connect/certs



