package br.edu.ufape.hvu.model.enums;

public enum TipoFicha {
    FICHA_DE_ATENDIMENTO_CARDIOLOGICO,
    FICHA_CLINICA_MEDICA,
    FICHA_CLINICA_DERMATOLOGICA,
    FICHA_DE_ATENDIMENTO_ORTOPEDICO,
    FICHA_CLINICA_MEDICA_DE_ANIMAIS_SILVESTRES_E_EXOTICOS,
    FICHA_REABILITACAO_INTEGRATIVA,
    FICHA_DE_ATO_CIRURGICO,
    FICHA_CLINICA_DERMATOLOGICA_DE_RETORNO,
    FICHA_CLINICA_MEDICA_DE_RETORNO,
    FICHA_CLINICA_MEDICA_DE_RETORNO_DE_ANIMAIS_SILVESTRES_E_EXOTICOS,
    FICHA_DE_SOLICITACAO_DE_CITOLOGIA,
    FICHA_DE_SOLICITACAO_DE_EXAMES,
    FICHA_DE_EXAME_NEUROLOGICO_DE_PEQUENOS_ANIMAIS,
    TERMO_DE_CONSENTIMENTO_PARA_REALIZACAO_DE_EUTANASIA,
    TERMO_DE_CONSCIENTIZACAO_LIVRE_E_ESCLARECIDA_PARA_REALIZACAO_DO_PROCEDIMENTO_ANESTESICO
}
